### ISSUE TITLE
Tracking Issue: Initial Release

### ISSUE THREAD

**Issue by palday** [beacon-biosignals/Effects.jl#2]
We're spinning off our implementation of effects computations and releasing it to the community. Hooray! Here's what needs to happen:

Task list
- [x] Make this tracking issue :) 
- [x] No private info in code 
- [x] Pre-make public commit:
  - [x] Add MIT license
  - [x] Add tests + CI badge to README
 - [x] Make sure repo follows best-practice settings
  -  [x] Make docs build
   - [x] Add docs badges to README
  - [x] Add TagBot GitHub Action
  - [x] Add CompatHelper GitHub Action
- [x] Make repo public
- [x] Have @jrevels enable repo access for the general julia registrator
- [x] Open [PR in Julia registry]() 
  - [x] Wait for it to auto-merge (or have @ericphanson do a drive-by :smile:)
